### PR TITLE
Changes for ZenCash

### PR DESCRIPTION
**Pull request by LukasBures**
// TODO: Check port number!
rpcPort = 8234;

### CODE REVIEW

**Comment by LukasBures** [comment]
`var`s changed to `let`s - I hope all will works

Check it please

**Comment by LukasBures** [comment]
rpc port changed to 'rpcport=8231'

**Comment by LukasBures** [comment]
Functionality for restoring ZenCash from Zclassic wallet.dat was added

**Comment by xdemocle** [comment]
Can we expect also the build for mac then?

**Pull request merged**
